services:
  srf-api:
    container_name: srf-api
    image: srf/srf:1.0.1
    ports:
      - 8088:8088
    networks:
      - spring-demo
    environment:
      - ACTIVE_PROFILE=prod   # or prod depending on your use case
      - DB_URL=jdbc:postgresql://34.16.181.252:5432/sarafBRKdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=SarafBrkDb24$
      - APP_VERSION=1.0.1
      - EMAIL_HOSTNAME=smtp.gmail.com
      - EMAIL_USER_NAME=sarafbrk@gmail.com
      - EMAIL_USER_PASSWORD=ftrs nzhz bpnt vftp
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge