services:
  srf-api:
    container_name: srf-api
    image: srf/srf:1.0.1
    ports:
      - 8088:8088
    networks:
      - spring-demo
    environment:
      - ACTIVE_PROFILE=prod   # or prod depending on your use case
      - DB_HOST=34.16.181.252
      - DB_NAME=sarafBRKdb
      - DB_USER=postgres
      - APP_VERSION=1.0.1
      - MAIL_USERNAME=sarafbrk@gmail.com
      - MAIL_PASSWORD=ftrs nzhz bpnt vftp
      - CORS_ORIGINS_PROD=https://sarafbrk.com
      - ACTIVATION_URL=http://localhost:8088/api/v1/auth/activate-account?verToken=
      - JWT_SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge