services:
  srf-api:
    container_name: srf-container
    image: xuamine/srf-api:latest
    ports:
      - 8088:8088
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge