-- insert into _user (email, enabled, firstname, lastname, password, role, id)
-- values ('test@testing.com', true, 'mohamed', 'zirek', 'testing24$', 'ADMIN', 1001);
--
-- insert into _user (email, enabled, firstname, lastname, password, role, id)
-- values ('test1@testing.com', true, 'nejmou', 'zirek', 'testing26$', 'USER', 1002);
--
-- insert into recipient (ccp,do_contact,firstname,is_active,lastname,phone_number,user_id,id)
-- values ('12345678911', true, 'abdel rahim', true, 'zirek', '213664440342', 1001, 2001);
--
-- insert into exchange_rate (current_rate)
-- values (230);
--
-- insert into transfer (amount, amount_received, receipt, recipient_id, status, transfer_date, user_id, id)
-- values (400, 86000, null, 2001, 'PENDING', '2024-01-01', 1001, 3001);
