spring:
  datasource:
    url: jdbc:postgresql://sarafdb.c302gk4uasl6.us-west-1.rds.amazonaws.com:5432/sarafdb
    username: postgres
    password: SarafBrkDataBase24$
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 603364375521-ht159trgevgficpqua2a6jmqmfktq50f.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

  mail:
    host: smtp.porkbun.com
    port: 50587
    username: amine@sarafbrk.com
    password: SarafBrkAmine24$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 1200000 # 20 minute 1200000
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: https://api.arafbrk.com:8088/api/v1/auth/activate-account?verToken=
  cors:
    origins: http://127.0.0.1:5501,http://172.31.18.95:8088,https://sarafbrk.com
  telegram:
    bot-token: 7432332647:AAGVk09oaTxAA_ZqtCbnCwbzHVcpPIQAjRI
    channel-id: -1002196827583

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.core.env: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
  file:
    name: /var/log/spring-boot-app/app.log

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  prometheus:
    metrics:
      export:
        enabled: true

server:
  ssl:
    key-store: keystore.p12
    key-store-password: saraf
    key-store-type: PKCS12
    key-alias: saraf
  port: 8088