spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 50MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_SECRET}
            scope: public_profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"

springdoc:
  default-produces-media-type: application/json
