spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 603364375521-ht159trgevgficpqua2a6jmqmfktq50f.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          facebook:
            client-id: 1055232082490271
            client-secret: 2efda36eb8cfd084ac3f59d5de367de8
            scope: public_profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"

  mail:
    host: smtp.porkbun.com
    port: 50587
    username: amine@sarafbrk.com
    password: SarafBrkAmine24$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 1200000 # 20 minute 1200000
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: ${ACTIVATION_URL_PROD}
  cors:
    origins: ${CORS_ORIGINS_PROD}

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org:
      springframework:
        security: DEBUG
        web: DEBUG
  file:
    name: /var/log/spring-boot-app/app.log

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  prometheus:
    metrics:
      export:
        enabled: true

server:
  ssl:
    key-store: keystore.p12
    key-store-password: saraf
    key-store-type: PKCS12
    key-alias: saraf
  port: 8088
#  address: 0.0.0.0


