spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 50MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID_PROD}
            client-secret: ${GOOGLE_SECRET_PROD}
            scope: profile, email
            redirect-uri: "https://sarafbrk.com/recipient/"
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_SECRET}
            scope: public_profile, email
            redirect-uri: "https://sarafbrk.com/recipient/"

springdoc:
  default-produces-media-type: application/json
