spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 1200000 # 20 minute 1200000
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: ${ACTIVATION_URL_PROD}
  cors:
    origins: ${CORS_ORIGINS_PROD}

logging:
  level:
    root: INFO
    org.springframework.web: WARN
  file:
    name: /var/log/spring-boot-app/app.log

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  prometheus:
    metrics:
      export:
        enabled: true

server:
  ssl:
    key-store: keystore.p12
    key-store-password: saraf
    key-store-type: PKCS12
    key-alias: saraf
  port: 8088
  address: 0.0.0.0


