spring:
  datasource:
    url: jdbc:postgresql://sarafdb.c302gk4uasl6.us-west-1.rds.amazonaws.com:5432/sarafdb
    username: postgres
    password: SarafBrkDataBase24$
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID_PROD}
            client-secret: ${GOOGLE_SECRET_PROD}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID_PROD}
            client-secret: ${FACEBOOK_SECRET_PROD}
            scope: public_profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"

  mail:
    host: smtp.porkbun.com
    port: 50587
    username: ${MAIL_USERNAME_PROD}
    password: ${MAIL_PASSWORD_PROD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 1200000 # 20 minute 1200000
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: ${ACTIVATION_URL_PROD}
  cors:
    origins: ${CORS_ORIGINS_PROD}
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN}
    channel-id: ${TELEGRAM_CHANNEL_ID}

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.core.env: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
  file:
    name: /var/log/spring-boot-app/app.log

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  prometheus:
    metrics:
      export:
        enabled: true

server:
  ssl:
    key-store: keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: saraf
  port: 8088